services:
  db:
    image: mysql:8.0
    container_name: mysql_db2
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'JPA'
      MYSQL_DATABASE: 'JPADB'
      MYSQL_USER: 'JPA'
      MYSQL_PASSWORD: 'JPA'
    ports:
      - '3309:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: